# Generated by Django 2.2.5 on 2019-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authority',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'visitor')], default=3, help_text='権限', verbose_name='権限'),
        ),
    ]
