# Generated by Django 2.2.5 on 2019-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='未入力', max_length=30, null=True, verbose_name='ユーザー'),
        ),
    ]
